### ISSUE TITLE
[Tracking Issue] L2 coverage

### ISSUE THREAD

**Issue by Chriscbr** [cdk8s-team/cdk8s#2191]
This is a preliminary list of some of the configuration options available in the core Kubernetes resources that we think might be convenient to be able to configure with the hand-crafted, higher-level APIs of cdk8s+. We're looking for your support to help us prioritize which features would be most useful by giving +1s reactions (thumbs up reaction) on the linked issues!

This list was collected based on a surface-level review of the Kubernetes specification and docs, so it's possible there are errors or missing features. We also omitted several alpha/beta APIs (but if these interest you, feel free to create issues for them and we can add them to the list). If you see items that don't make sense, or which could be combined together as part of a higher-level abstraction, please leave a comment here or in the linked issues. Thanks!

## Missing resource types

- [x] We have constructs for defining [role-based access control](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) (RBAC) API objects.
  - [x] https://github.com/cdk8s-team/cdk8s-plus/issues/24
  - [x] https://github.com/cdk8s-team/cdk8s-plus/issues/25
  - [x] https://github.com/cdk8s-team/cdk8s-plus/issues/374
  - [x] https://github.com/cdk8s-team/cdk8s-plus/issues/26
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/375
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/376
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/446
- [ ] https://github.com/cdk8s-team/cdk8s-plus/issues/419

## ConfigMap

- [x] We support creating ConfigMap with data and binaryData directly
- [x] We support creating / supplying ConfigMap with data from files or directories as data.
- [x] We support using ConfigMap to supply individual environment variables to pods.
- [x] We support using ConfigMap to create volumes for pods.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/341

## Secret

- [x] We support creating secrets from string data and configuring secret types.
- [x] We support defining environment values from secret (JSON) values.
- [x] We support using Secrets to create volumes for pods.
- [x] We support using Secrets to supply environment variables to pods.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/342
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/343
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/344

## Probe

- [x] We support creating probes that check if an HTTP get request to the IP address of a container succeeds.
- [x] We support creating probes that check if a command successfully executes within a container.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/345

## Container

- [x] We support supplying entrypoint args to containers.
- [x] We support supplying entrypoint command to containers.
- [x] We support supplying individual environment values to containers using env.
- [x] We support attaching liveness probes, readiness probes, and startup probes to containers.
- [x] We support configuring the names of containers.
- [x] We support configuring the ports of containers.
- [x] We support specifying the container working directory.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/346
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/27
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/183
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/347
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/348

## Volume

- [x] We support creating volumes from ConfigMaps.
- [x] We support creating EmptyDir volumes.
- [x] We support creating Secret volumes.
- [x] We support using subPath to share a volume for multiple uses within a single pod.
- [x] We support configuring mount propagation.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/349
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/350
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/351
- [ ] https://github.com/cdk8s-team/cdk8s-plus/issues/352
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/176
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/353
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/354
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/355
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/356

## Pod

- [x] We support configuring the restart policy of pods.
- [x] We support configuring the service account used to run a pod.
- [x] We support adding containers to pods.
- [x] We support adding volumes to pods.
- [x] We support customizing the restart policy of pods.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/30
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/358
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/359
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/31
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/377
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/360
- [ ] https://github.com/cdk8s-team/cdk8s-plus/issues/361
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/362
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/378
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/348
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/418

## Deployment

- [x] We support exposing a deployment via a service.
- [x] We support automatically allocating a pod selector for a deployment.
- [x] We support configuring the desired number of pods in a deployment (replicas).
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/364
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/365

For other customizations related to the Pod spec, check the Pod section above. ⬆️ 

## Ingress

- [x] We support configuring routing rules for ingresses.
- [x] We support configuring TLS settings for ingresses.
- [x] We support configuring various services as ingress backends.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/366
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/367

## Job

- [x] We support configuring the max duration of jobs (activeDeadlineSeconds).
- [x] We support configuring a maximum number of retries for jobs (backoffLimit).
- [x] We support configuring the lifetime of finished jobs (ttlAfterFinished).
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/368

## Service

- [x] We support customizing the IP address assigned to a service.
- [x] We support specifying the IPs of nodes that will accept traffic for the service.
- [x] We support customizing the ports exposed by the service.
- [x] We support exposing services via an ingress, and specifying the type of service it is.
- [x] We support adding selectors to choose pods for this service.
- [x] We support associating a deployment with a service.
- [x] We support specifying the external name of a service.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/369
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/370
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/371

## ServiceAccount

- [x] We support configuring the secrets that can be used by a service account.
- [x] We support configuring the service account used to run a pod.

## StatefulSet

- [x] We support configuring the service associated with a StatefulSet.
- [x] We support configuring the desired number of pods in a StatefulSet.
- [x] We support automatically allocating selectors for a StatefulSet.
- [x] We support customizing the pod management policy of a StatefulSet.
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/372
- [x] https://github.com/cdk8s-team/cdk8s-plus/issues/373
